"""
Agent 4: The Archivist — Living Context Maintainer.
Generates CODEBASE.md, onboarding_brief.md, serialized lineage graph,
and cartography_trace.jsonl audit log.

Status: STUB — full generation in Phase 4.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from loguru import logger

from src.models.graph import CartographyResult


class Archivist:
    """
    Artifact generation agent.

    Usage:
        archivist = Archivist(output_dir=Path(".cartography"))
        archivist.write_all(result)
    """

    def __init__(self, output_dir: Path):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self._trace_path = self.output_dir / "cartography_trace.jsonl"

    # ─── CODEBASE.md ──────────────────────────────────────────────────

    def generate_codebase_md(self, result: CartographyResult) -> str:
        """
        Produce the living context file for AI coding agent injection.

        Sections:
            1. Architecture Overview
            2. Critical Path (top 5 by PageRank)
            3. Data Sources & Sinks
            4. Known Debt (circular deps + doc drift)
            5. High-Velocity Files
            6. Module Purpose Index
        """
        pr = result.module_graph.pagerank_scores
        top5 = sorted(pr, key=pr.get, reverse=True)[:5] if pr else []

        sources = result.lineage_graph.source_datasets
        sinks = result.lineage_graph.sink_datasets

        sccs = result.module_graph.strongly_connected_components
        circular = "\n".join(f"  - {' → '.join(c)}" for c in sccs) if sccs else "  None detected"

        top_velocity = result.high_velocity_files[:10]
        velocity_list = "\n".join(f"  - {f}" for f in top_velocity) or "  None detected"

        module_index = "\n".join(
            f"  - **{path}**: {node.purpose_statement or '(not yet analysed)'}"
            for path, node in list(result.module_graph.modules.items())[:30]
        )

        domains = "\n".join(
            f"  - **{domain}** ({len(mods)} modules)"
            for domain, mods in result.domain_clusters.items()
        )

        md = f"""# CODEBASE.md — {result.repo_name}
> Auto-generated by Brownfield Cartographer on {result.analysis_timestamp}
> Inject this file as system context into any AI coding agent for instant architectural awareness.

---

## 1. Architecture Overview

This repository contains **{len(result.module_graph.modules)} modules** across multiple languages.
Analysis identified **{len(result.domain_clusters)} domain clusters** and
**{len(result.lineage_graph.datasets)} datasets** in the data lineage graph.

## 2. Critical Path (Top Modules by PageRank)

{"".join(f"  {i+1}. `{m}`\\n" for i, m in enumerate(top5)) or "  Not yet computed."}

## 3. Data Sources & Sinks

**Sources (entry points):**
{"".join(f"  - `{s}`\\n" for s in sources) or "  None detected."}

**Sinks (output datasets):**
{"".join(f"  - `{s}`\\n" for s in sinks) or "  None detected."}

## 4. Known Debt

**Circular Dependencies:**
{circular}

**Documentation Drift:**
  Modules where LLM-generated purpose diverges from docstring:
  - (Phase 3 output — not yet generated)

## 5. High-Velocity Files (Likely Pain Points)

{velocity_list}

## 6. Domain Architecture Map

{domains or "  (Phase 3 clustering — not yet generated)"}

## 7. Module Purpose Index (first 30)

{module_index}
"""
        return md.strip()

    def write_codebase_md(self, result: CartographyResult) -> Path:
        content = self.generate_codebase_md(result)
        path = self.output_dir / "CODEBASE.md"
        path.write_text(content, encoding="utf-8")
        logger.info(f"[Archivist] CODEBASE.md → {path}")
        self._log_trace("write_codebase_md", {"path": str(path)})
        return path

    # ─── onboarding_brief.md ──────────────────────────────────────────

    def write_onboarding_brief(self, result: CartographyResult) -> Path:
        """Generate the Day-One FDE onboarding brief."""
        answers = result.day_one_answers
        content = f"""# FDE Day-One Onboarding Brief — {result.repo_name}
> Generated: {result.analysis_timestamp}

---

## Q1: Primary Data Ingestion Path
{answers.get("Q1_ingestion_path", "_Not yet generated_")}

## Q2: Critical Output Datasets / Endpoints
{answers.get("Q2_critical_outputs", "_Not yet generated_")}

## Q3: Blast Radius if Most Critical Module Fails
{answers.get("Q3_blast_radius", "_Not yet generated_")}

## Q4: Business Logic — Concentrated vs Distributed
{answers.get("Q4_business_logic", "_Not yet generated_")}

## Q5: Git Velocity Map (Last 90 Days)
{answers.get("Q5_git_velocity", "_Not yet generated_")}

---
*All answers include evidence citations (file path + line range) where available.*
"""
        path = self.output_dir / "onboarding_brief.md"
        path.write_text(content, encoding="utf-8")
        logger.info(f"[Archivist] onboarding_brief.md → {path}")
        self._log_trace("write_onboarding_brief", {"path": str(path)})
        return path

    # ─── Serialized Graphs ────────────────────────────────────────────

    def write_module_graph(self, result: CartographyResult) -> Path:
        path = self.output_dir / "module_graph.json"
        path.write_text(result.module_graph.model_dump_json(indent=2), encoding="utf-8")
        logger.info(f"[Archivist] module_graph.json → {path}")
        return path

    def write_lineage_graph(self, result: CartographyResult) -> Path:
        path = self.output_dir / "lineage_graph.json"
        path.write_text(result.lineage_graph.model_dump_json(indent=2), encoding="utf-8")
        logger.info(f"[Archivist] lineage_graph.json → {path}")
        return path

    # ─── Write All ────────────────────────────────────────────────────

    def write_all(self, result: CartographyResult) -> None:
        """Write all cartography artifacts to output_dir."""
        self.write_module_graph(result)
        self.write_lineage_graph(result)
        self.write_codebase_md(result)
        self.write_onboarding_brief(result)
        logger.info(f"[Archivist] All artifacts written to {self.output_dir}")

    # ─── Trace Log ────────────────────────────────────────────────────

    def _log_trace(self, action: str, metadata: dict[str, Any]) -> None:
        """Append a JSONL audit event to cartography_trace.jsonl."""
        entry = {
            "timestamp": datetime.now(tz=timezone.utc).isoformat(),
            "action": action,
            **metadata,
        }
        with self._trace_path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
